version: '3.8'

services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '[ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]',
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  dynamodb-init:
    image: amazon/aws-cli
    container_name: dynamodb-init
    depends_on:
      dynamodb-local:
        condition: service_healthy
    volumes:
      - ./license-dynamo-table.json:/tmp/license-dynamo-table.json
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=eu-central-1
    entrypoint: ['/bin/sh', '-c']
    command: >
      "aws dynamodb create-table --cli-input-json file:///tmp/license-dynamo-table.json 
      --endpoint-url=http://dynamodb-local:8000 --region eu-central-1 --no-cli-pager"

  s3:
    image: minio/minio
    ports:
      - '9000:9000'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data
    volumes:
      - minio-data:/data

volumes:
  minio-data:
